services:
  cv-webpage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-webpage
    ports:
      - "5110:5110"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cv-cloudflared
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - C:/Users/flyin/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - cv-webpage
    restart: unless-stopped
